replaced metadata.tsv with bcl2fastq output files
- Demultiplex_Stats.csv
- fastq_list.csv

diff --git a/images/fastcat-nodejs/scripts/consolidate-metadata b/images/fastcat-nodejs/scripts/consolidate-metadata
--- a/images/fastcat-nodejs/scripts/consolidate-metadata
+++ b/images/fastcat-nodejs/scripts/consolidate-metadata
@@ -5,54 +5,70 @@ env
 
 [[ "${DEBUG:-}" ]] && set -x
 
+# check for existence of required env. vars.
+: "$FASTCAT_S3URL_OUTPUT_PREFIX" # e.g. s3://hkgi-fastq-test2/outputs
+: "$FASTCAT_S3URL_JOBS_PREFIX" # e.g. s3://hkgi-fastq-test2/dev/jobs
 
-(( $# == 3 )) || {
+
+(( $# == 1 )) || {
     cat >&2 <<EOF
-$0: <job_tgz> <stats_prefix> <fastq_prefix>
-1) Download the job descriptions in <job_tgz> from S3.
+$0: <job_file_s3>
+1) Download the job file from S3.
 2) Download statistics (incl. MD5) from S3.
 3) Consolidate statistics, generate metadata file and upload the MD5 to S3.
 
 where
-    <job_tgz> is an s3:// URL to the job descriptions
-    <stats_prefix> is an s3:// URL prefix to the statistics
-    <FASTQ_prefix> is an s3:// URL prefix to the concatenated FASTQ files; the
-                   generated metadata file would be uploaded here
+    <job_file_s3>  is an s3:// URL to the job file
+
+Environment variables *required*:
+    FASTCAT_S3URL_OUTPUT_PREFIX (format: s3://<bucket>/<prefix>)
+        S3 URL prefix for output metadata file
+    FASTCAT_S3URL_JOBS_PREFIX (format: s3://<bucket>/<prefix>)
+        S3 URL prefix for intermediate files of jobs
 EOF
 
     exit 1
 }
 
 
-job_tgz_url="$1"
-stats_prefix="$2"
-fastq_prefix="$3"
+job_file_url="$1"
+
+cd /tmp
+aws s3 cp "$job_file_url" job.json
+
+
+job_id="$(jq -r '.job_id' < job.json)"
+batch_id="$(jq -r '.batch_id' < job.json)"
+[[ -n "$job_id" ]] || {
+    echo "cannot determine job id from $job_file_url" >& 2
+    exit 1
+}
+[[ -n "$batch_id" ]] || {
+    echo "cannot determine batch id from $job_file_url" >& 2
+    exit 1
+}
+
+stats_prefix="$FASTCAT_S3URL_JOBS_PREFIX/$job_id"
+fastq_prefix="$FASTCAT_S3URL_OUTPUT_PREFIX/$batch_id"
 
 stats_out_url="$fastq_prefix/metadata.tsv"
 
-cd /tmp
-aws s3 cp "$job_tgz_url" job.tgz
 aws s3 sync "$stats_prefix" stats/
 stats_dir="$(realpath stats)"
 
-mkdir -p job
-cd job
-job_dir="$(realpath .)"
-tar xvf ../job.tgz
 
-job_id="$(cat job.id)"
 [[ -n "$job_id" ]] || {
-    echo "cannot determine job id from $job_tgz_url" >& 2
+    echo "cannot determine job id from $job_file_url" >& 2
     exit 1
 }
 echo "job $job_id consolidation"
 
 
 node --enable-source-maps /opt/nodejs/dist/meta-formatter.js \
-     "$job_dir" \
+     "./job.json" \
      "$stats_dir" \
      "$fastq_prefix" \
-     "$job_dir/metadata.tsv"
+     "./metadata.tsv"
 
 aws s3 cp metadata.tsv "$stats_out_url"
 
diff --git a/images/fastcat-nodejs/scripts/process-metadata b/images/fastcat-nodejs/scripts/process-metadata
--- a/images/fastcat-nodejs/scripts/process-metadata
+++ b/images/fastcat-nodejs/scripts/process-metadata
@@ -15,12 +15,15 @@ env
 
 (( $# == 1 )) || {
     cat >&2 <<EOF
-$0: <metadata>
-Parse input metadata file and create files needed for
-the jobs to be spawned
+$0: <fastq_list>
+Parse input metadata files and create a job file containing
+data for the jobs to be spawned
 
 where
-    <metadata> is an s3:// URL to the input metadata file
+    <fastq_list> is an s3:// URL to the input fastq_list.csv;
+                 the accompanying Demultiplex_Stats.csv file is
+                 assumed to be found under the same directory;
+                 All input fastq.gz files should also be found there.
 
 Environment variables *required*:
     FASTCAT_S3URL_OUTPUT_PREFIX (format: s3://<bucket>/<prefix>)
@@ -38,75 +41,64 @@ EOF
     exit 1
 }
 
-metadata_url="$1"
+fqlist_url="$1"
 
-job_rand="$(uuidgen | cut -d- -f1)"
+job_rand="$(echo "${AWS_BATCH_JOB_ID:-$(uuidgen)}" | cut -d- -f1)"
 job_ts="$(TZ=UTC date +%Y%m%d-%H%M%S)"
 job_id="$job_ts-$job_rand"
-batch_id="${metadata_url%/*}"
-batch_id="${batch_id##*/}"
+in_dir_url="${fqlist_url%/*}"
+demux_url="$in_dir_url/Demultiplex_Stats.csv"
+batch_id="${in_dir_url##*/}"
 
 [[ "$batch_id" ]] || {
-    echo "Cannot derive batch id from: $metadata_url" >& 2
+    echo "Cannot derive batch id from: $fqlist_url" >& 2
     exit 1
 }
 
-output_s3="$FASTCAT_S3URL_OUTPUT_PREFIX/$batch_id"
 job_s3="$FASTCAT_S3URL_JOBS_PREFIX/$job_id"
+job_file_s3="$job_s3/job.json"
 
 
 mkdir -p /tmp/job/data
 cd /tmp/job
 
 
-aws s3 cp "$metadata_url" metadata.tsv
+aws s3 cp "$fqlist_url" fqlist.csv
+aws s3 cp "$demux_url"  demux.csv
 
-node --enable-source-maps /opt/nodejs/dist/meta-parser.js \
-     metadata.tsv \
-     data
+node --enable-source-maps /opt/nodejs/dist/bcl2fq-metadata-parser.js \
+     demux.csv fqlist.csv \
+     "$in_dir_url" "$job_id" "$batch_id" \
+     job.json
 
-echo "$job_id" > data/job.id
+aws s3 cp job.json "$job_file_s3"
 
-tar zcvf - -C data . |\
-    aws s3 cp - "$job_s3.tgz"
+nr_subjobs="$(jq '.jobs | length' < job.json)"
 
-nr_subjobs="$(find data/ -name 'job.*.data' | wc -l)"
 
-declare -a params=(
-    "job_tgz_s3_url=$job_s3.tgz"
-    "FASTQ_out_prefix=$output_s3"
-    "MD5_out_prefix=$job_s3"
-)
 ${NO_SUBMIT_JOBS:+echo Not submitting: } \
 aws batch submit-job \
-    --query jobId --output text \
     --job-name "fastcat-$job_id" \
     --job-queue "$FASTCAT_JOB_QUEUE_ARN" \
     --job-definition "$FASTCAT_CONCAT_JOB_DEF_ARN" \
-    --parameters "$(IFS=","; echo "${params[*]}")" \
+    --parameters "job_file_s3_url=$job_file_s3" \
     --array-properties "size=$nr_subjobs" |\
-    tee concat-job.id
+    tee concat-job.json
 if [[ "${NO_SUBMIT_JOBS:-}" ]]; then
     concat_job_id="(unsubmitted)"
 else
-    concat_job_id="$(cat concat-job.id)"
+    concat_job_id="$(jq -r ".jobId" < concat-job.json)"
 fi
 #FIXME:    --tags ???
 
 
-declare -a params=(
-    "job_file_s3_url=$job_s3.tgz"
-    "stats_s3_url_prefix=$job_s3"
-    "fastq_s3_url_prefix=$output_s3"
-)
 ${NO_SUBMIT_JOBS:+echo Not submitting: } \
 aws batch submit-job \
     --job-name "fastcat-consolidate-$job_id" \
     --job-queue "$FASTCAT_JOB_QUEUE_ARN" \
     --job-definition "$FASTCAT_METADATA_GENERATION_JOB_DEF_ARN" \
-    --parameters "$(IFS=","; echo "${params[*]}")" \
+    --parameters "job_file_s3_url=$job_file_s3" \
     --depends-on "jobId=$concat_job_id,type=SEQUENTIAL"
-
 #FIXME:    --tags ???
 
 #end
diff --git a/images/fastcat/scripts/concat-fastq b/images/fastcat/scripts/concat-fastq
--- a/images/fastcat/scripts/concat-fastq
+++ b/images/fastcat/scripts/concat-fastq
@@ -5,19 +5,27 @@ env
 
 [[ "${DEBUG:-}" ]] && set -x
 
+# check for existence of required env. vars.
+: "$FASTCAT_S3URL_OUTPUT_PREFIX" # e.g. s3://hkgi-fastq-test2/outputs
+: "$FASTCAT_S3URL_JOBS_PREFIX" # e.g. s3://hkgi-fastq-test2/dev/jobs
 
-(( $# == 3 )) || {
+
+(( $# == 1 )) || {
     cat >&2 <<EOF
-$0: <job_tgz> <FASTQ_out_prefix> <stats_out_prefix>
-1) Download the job descriptions in <job_tgz> from S3.
+$0: <job_file_s3>
+1) Download the job descriptions in <job_file_s3> from S3.
 2) create one concatenated FASTQ.gz file as a subjob of an AWS Batch Job array
    and upload it to S3.
 3) upload the MD5 to S3.
 
 where
-    <job_tgz> is an s3:// URL to the job descriptions
-    <FASTQ_out_prefix> is an s3:// URL prefix to upload the concatenated output file
-    <stats_out_prefix> is an s3:// URL prefix to upload the statistics and MD5
+    <job_file_s3> is an s3:// URL to the job file
+
+Environment variables *required*:
+    FASTCAT_S3URL_OUTPUT_PREFIX (format: s3://<bucket>/<prefix>)
+        S3 URL prefix for output, concatenated FASTQ.gz file
+    FASTCAT_S3URL_JOBS_PREFIX (format: s3://<bucket>/<prefix>)
+        S3 URL prefix for intermediate files of jobs
 EOF
 
     exit 1
@@ -26,39 +34,46 @@ EOF
 
 upload_chunk_size=$((128 * 1024 * 1024)) # 128MB
 
-metadata_url="$1"
-FASTQ_out_prefix="$2"
-stats_out_prefix="$3"
 job_index="${FASTCAT_JOB_ARRAY_INDEX:-${AWS_BATCH_JOB_ARRAY_INDEX:?This script should be run in a AWS Batch *Array* job}}"
+job_file_url="$1"
 
 
 cd /tmp
-aws s3 cp "$metadata_url" job.tgz
+aws s3 cp "$job_file_url" job.json
 
-mkdir -p job
-cd job
-tar xvf ../job.tgz
 
-job_id="$(cat job.id)"
+input_s3_url_prefix="$(jq -r '.input_s3_url_prefix' < job.json)"
+job_id="$(jq -r '.job_id' < job.json)"
+batch_id="$(jq -r '.batch_id' < job.json)"
+[[ -n "$input_s3_url_prefix" ]] || {
+    echo "cannot determine input S3 URL prefix from $job_file_url" >& 2
+    exit 1
+}
 [[ -n "$job_id" ]] || {
-    echo "cannot determine job id from $metadata_url" >& 2
+    echo "cannot determine job id from $job_file_url" >& 2
+    exit 1
+}
+[[ -n "$batch_id" ]] || {
+    echo "cannot determine batch id from $job_file_url" >& 2
     exit 1
 }
 echo "job $job_id subjob $job_index"
 
-job_file_base="job.$job_index"
-job_data_file="$job_file_base.data"
-lib_id="$(grep ^libid "$job_data_file" | cut -f2)"
-read_end="$(grep ^end "$job_data_file" | cut -f2)"
-[[ -n "$lib_id" && -n "$read_end" ]] || {
-    echo "cannot determine lib ID or read end from $metadata_url"
+output_s3_url_prefix="$FASTCAT_S3URL_OUTPUT_PREFIX/$batch_id"
+job_s3_prefix="$FASTCAT_S3URL_JOBS_PREFIX/$job_id"
+
+
+jq ".jobs[$job_index]" < job.json > subjob.json
+sample="$(jq -r '.sample' < subjob.json)"
+read_end="$(jq -r '.end' < subjob.json)"
+[[ -n "$sample" && -n "$read_end" ]] || {
+    echo "cannot determine lib ID or read end from $job_file_url"
     exit 1
 }
-echo "for $lib_id read $read_end"
+echo "for $sample read $read_end"
 
-job_files_file="$job_file_base.files"
-mapfile -t file_s3_urls < <(cut -f2 "$job_files_file")
-mapfile -t read_counts  < <(cut -f1 "$job_files_file")
+mapfile -t read_counts < <(jq   '.counts | .[]' < subjob.json)
+mapfile -t files  < <(jq -r '.files | .[]' < subjob.json)
 
 
 
@@ -71,34 +86,33 @@ wait_for_file() {
 }
 
 s3_concat_and_count_reads() {
-    local linecount_file
-
-    for i in "${!file_s3_urls[@]}"; do
-        local s3_url="${file_s3_urls[i]}"
-        local linecount_file="line_count.$i"
-        aws s3 cp "$s3_url" - |\
-            tee >(zcat | wc -l > "$linecount_file.tmp" &&
-                      mv -i "$linecount_file"{.tmp,})
-    done
-
-    # verify read counts
     local total_reads=0
-    for i in "${!file_s3_urls[@]}"; do
-        local s3_url="${file_s3_urls[i]}"
+
+    for i in "${!files[@]}"; do
+        local file="${files[i]}"
         local read_count_expected="${read_counts[i]}"
-        local linecount_file="line_count.$i"
-        wait_for_file "$linecount_file"
+        local s3_url="$input_s3_url_prefix/$file"
+        local line_count_file=./line_count.tmp
+
+        rm -f "$line_count_file"
+        aws s3 cp "$s3_url" - |\
+            tee >(zcat | wc -l > "$line_count_file.tmp" &&
+                      mv -f "$line_count_file"{.tmp,})
+        wait_for_file "$line_count_file"
 
         local lines
-        lines="$(cat "$linecount_file")"
+        lines="$(cat "$line_count_file")"
         ((lines % 4 == 0)) || {
             echo "Line count ($lines) is not a multiple of 4... truncated file? <== $s3_url" >& 2
             exit 1
         }
+
         local read_count_found=$((lines / 4))
         ((total_reads += read_count_found))
-
-        ((read_count_expected < 1)) && continue
+        ((read_count_expected < 1)) && {
+            echo "$read_count_found reads found <== $s3_url" >&2
+            continue
+        }
 
         ((read_count_found == read_count_expected)) || {
             echo "Read count mismatch (expected=$read_count_expected found=$read_count_found) <== $s3_url" >& 2
@@ -122,13 +136,13 @@ calc_md5() {
 
 
 
-fastq_base="${lib_id}_${read_end}"
-out_url="$FASTQ_out_prefix/$fastq_base.fastq.gz"
-stats_out_url="$stats_out_prefix/$fastq_base.fastq.stats"
+fastq_base="${sample}_${read_end}"
+out_url="$output_s3_url_prefix/$fastq_base.fastq.gz"
+stats_out_url="$job_s3_prefix/$fastq_base.fastq.stats"
 
 
-echo "Concatenating $fastq_base ..."
-for i in "${file_s3_urls[@]}"; do
+echo "Concatenating from $input_s3_url_prefix ..."
+for i in "${files[@]}"; do
     echo "  $i"
 done
 echo "==>$out_url"
